### ISSUE TITLE
Instructions popup in JSON Survey still has old instructions

### ISSUE THREAD

**Issue by MichaelKentBurns** [MichaelKentBurns/MKB-cohort-1-Demo#21]
In the JSON Survey page, if I click on 'Instructions here' I get a popup with the following text:

`Welcome to MKB-cohort-1-Demo . In this part you are going to follow these steps:
1. If you have already cloned the MKB-cohort-1-Demo, Open VS code 
2. Go to the extension and search for the live server
3. Install the extention
4. Then go to the Demo-JSON in your local and open it with VS code
5. Go to the jsonjavascript.html inside VS code
6. Right click inside the file
7. Click open with live server and everything will be displayed`

I think the user should not have to do any of this with our new demo setup.
Instead it should tell them to answer the questions and press the 'Submission' button.   Then it should show the json file below that button.   Finally there should be a view of the json data followed by the 'Save Survey Results (JSON)' link.  When that is pressed the json file should be downloaded to the user's downloads directory AND sent to the server where it will be stored in the database.   If that works a dialog with 'Survey results saved successfully!' otherwise '?? error message here ??' and a Close button. 
The user should click close and then use the browser back button to return to the main demo page.

**Comment by efatha** [comment]
**Issue Resolved.** 
I'm glad to announce that this issue regarding the popup in the JSON Survey Alert box has been addressed! The popup has been successfully updated.
**Changes implemented :**

-The popup text has been revised to provide more specific guidance on completing the survey.

- The layout of the popup has been adjusted to improve readability.
