### ISSUE TITLE
Need site certificate installed.

### ISSUE THREAD

**Issue by MichaelKentBurns** [MichaelKentBurns/MKB-cohort-1-Demo#24]
Samuel said in his survey form:

"Have you had any problems so far accessing this survey? If so breifly describe them." : "Yes! the problem that i have found it concern the security of this page, my software of protection had to notify me that, ..."

I need to get a certificate and apply it to this site.
Will do...

**Comment by AshDest** [comment]
I was about to start this, but I have paused the process to allow you to proceed. I had not seen the issue yet.

I had already installed this package :
`sudo apt install certbot python3-certbot-apache`

**Comment by MichaelKentBurns** [comment]
Feel free to proceed. Sent from my iPhone512-785-4684On Jul 5, 2024, at 04:51, Destin ASHUZA ***@***.***> wrote:﻿
I was about to start this, but I have paused the process to allow you to proceed. I had not seen the issue yet.
I had already installed this package :
sudo apt install certbot python3-certbot-apache

**Comment by MichaelKentBurns** [comment]
Hmmm.   I'm looking into this today and thought I generated the certificates needed.  Then when I was installing them,  or was trying to install them, I noticed there were already cert files in place.  Dated today.    

It looks like you (Ash) might have generated them because in my browsers when I look at the certificate it shows this: 
![Screenshot 2024-07-09 at 5 51 59 PM](https://github.com/MichaelKentBurns/MKB-cohort-1-Demo/assets/5041124/38335bde-7ade-450a-a7c6-84fcbd8c7d51)

Does this make sense to you?  
It's odd because the Country is US but the state is NK and Locality is Goma.   
![Screenshot 2024-07-09 at 5 51 59 PM](https://github.com/MichaelKentBurns/MKB-cohort-1-Demo/assets/5041124/50bbe9b4-e6ed-4c2b-9525-b902d56f8dc0)

**Comment by MichaelKentBurns** [comment]
My browser says this is not trusted.    That could maybe a mismatch of the state, city, and country.    These details are new to me.   

I've been using these documents today.
https://www.namecheap.com/support/knowledgebase/article.aspx/9423/33/installing-an-ssl-certificate-on-apache/
https://www.namecheap.com/support/knowledgebase/article.aspx/10026/33/installing-an-ssl-certificate-on-xampp/

It's a bit confusing because XAMPP does use Apache.

**Comment by MichaelKentBurns** [comment]
I found this URL that allows you to decode a certificate:

https://decoder.link/result

Here is a certificate that I generated today:
-----BEGIN CERTIFICATE REQUEST-----
MIIDDzCCAfcCAQAwgakxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJBWjEQMA4GA1UE
BwwHUGhvZW5peDEdMBsGA1UECgwUTWljaGFlbEtlbnRCdXJucy5jb20xDTALBgNV
BAsMBGRlbW8xIjAgBgNVBAMMGWRlbW8uTWljaGFlbEtlbnRCdXJucy5jb20xKTAn
BgkqhkiG9w0BCQEWGk1pY2hhZWxLZW50QnVybnNAZ21haWwuY29tMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs1WCa3BdKiKIYHSobIswBnbBgkODpPBs
3nXw63rGtTM8YeW8bPu+U7NzGGqfGJLVyVcDtylU/EbUo19dermyC6r/+VP9ejss
4GkXK5Eg8EKxhS6JNHtVXTRaxB5N/nic0TqkM9fEsFV4vtbjRXfBu2ZMP4ppgvIn
V4AAV5a3L6+nfOsAZtMKOo/nhJbJCoV6QyIkeQL3rLmB3+tGQgZVjcKCgpSn1S8Y
McTy05s73pLAvLLOx7v9KpelrhjrxOueqjWD79j3av/8OsfksOaec5mNm7SzRlgC
/mIKS9AQj8VTvYGl02Q17axDp3W4krrub9TgkExjW0VhTHcJrbOj5QIDAQABoCAw
HgYJKoZIhvcNAQkHMREMD21lQW5kSGlzSG91c2UyNDANBgkqhkiG9w0BAQsFAAOC
AQEAcx7HREv5mbWJ8nVijzCtSYJGQCtPndeulU/OXyojwUqzYxldmyzAgsIav4gS
JbbV2UzZE98bR2EmXgbQAfsxCk6jOWfcEIx/7dP0wJaVeZpfFg25W/RwxeqlvSse
A16yPSOud9a1jQH3VTupWDG2Res6UZgy8eZKWuLrAtgoNrjkLODPG1CLnCFKd5zs
vvH4f+oPINtUP46ViDNZSTPabEczlr3fuh1L2O0hJCAgIoNGHJGZyNT8Inu45rlT
tNzNSIVjL04Dm3mUhwI3NwEZ8tUO3k44U0eoxfsJ3hrS4/Sri7q7D+E7ZqSjBIT/
bO7siwUaa5PDKbG2RacYiuF9Qw==
-----END CERTIFICATE REQUEST-----

There are several others inside XAMPP (/opt/lampp):
michael@srv507169:/opt/lampp$ find . -name "*.crt" -ls
   132535      4 drwxr-xr-x   2 root     root         4096 Apr 11 22:48 ./etc/ssl.crt
   139303      4 -rw-r--r--   1 root     root         1066 Oct  1  2004 ./etc/ssl.crt/server.crt
   147262    212 -rw-r--r--   1 root     root       215352 May 30  2022 ./share/curl/curl-ca-bundle.crt
   528933      4 -rw-r--r--   1 root     root         1265 Jul  9 13:50 ./apache2/ssl/server.crt

The one that is installed in the server is: /opt/lampp/apache2/ssl/server.crt
-----BEGIN CERTIFICATE-----
MIIDeTCCAmGgAwIBAgIUTULJ3zRWVv9vjR3+pT3LG+d/dbQwDQYJKoZIhvcNAQEL
BQAwTDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAk5LMQ0wCwYDVQQHDARHb21hMSEw
HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMjQwNzA5MTM1MDIx
WhcNMjUwNzA5MTM1MDIxWjBMMQswCQYDVQQGEwJVUzELMAkGA1UECAwCTksxDTAL
BgNVBAcMBEdvbWExITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANHbF6XzbM/bEtnHU2zSWSLA
MM8gTlS/s+D/fpfF6PBWTHzIhdPde3Zz+na0zbuslCsdBZj0SBG7rYEMFs0yEOi4
oJ8QuyLETMaYJNE9ugYSBWr3aPN6himCt1t2WQlDmPG5OjJmY69UF0ViXWskPjsL
hzpu2X+wue45MGm2SP4fo7LHW58QxL54qSMkzvA7cnAzu/XRAJo4NWFGpu9EvWS+
ar/sxfNco/FMt9OUOR3+6vyeez1o5TYPgay2QyN6LsbfblsZHwA/Exn/IpZPGTqd
uklRUXMLofQnqELo/Q/bh5bZBBX5FSXpjj0zuGbJ99ekTvg2fPWYTBBIRSyoRF0C
AwEAAaNTMFEwHQYDVR0OBBYEFJ6OfEgJZyalVyvYHSiXCKGiLs6EMB8GA1UdIwQY
MBaAFJ6OfEgJZyalVyvYHSiXCKGiLs6EMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
hvcNAQELBQADggEBADPaNWYrZNqsjGXSFLBniLn9Ymb7EzglI0myV8soSW1fe5AX
KTZQygutsXoG9sPVQW5KprMOGyu0mkxtYo1BN0B6suG6IORxCPWOIAC0a69KXCh7
rB95W43eKfuvqCGuNevVJTI9cbLtk+OeExQym34ExcrW843KpF2QUrZE5FDfPlj0
5MHINqDPCjNlSph7cPqDheBeY+haZwMkZhGTPryvCZb4VtN7QUY9Xfplm0BNsQWC
z7ttMgRWGlWN+BtizGopX2lBn7hdVKZyNnXGDUKkiFwA/irlu1T8ZvrY0Yf7Zbq4
RxYT7aCvVK2ChdTbuCF0eEMrlfHuOkQlCuuUoTE=
-----END CERTIFICATE-----

If you decode that it is the one that I'm seeing when I point my browser at our site and look at the certificate being used.  This is the one from US / NK / Goma  that was generated today.

**Comment by AshDest** [comment]
>Hmmm. I'm looking into this today and thought I generated the certificates needed. Then when I was installing them, or was >trying to install them, I noticed there were already cert files in place. Dated today.
>
>It looks like you (Ash) might have generated them because in my browsers when I look at the certificate it shows this:

Exactly, this is coming from me. yesterday I too continued the ssl certification process,

**Comment by AshDest** [comment]
>Does this make sense to you?
>It's odd because the Country is US but the state is NK and Locality is Goma.

I generated a new key, but I wanted to know if it is important to specify the country and this other information

**Comment by MichaelKentBurns** [comment]
It needs to be created to properly reflect the actual location of the server.The reason a certificate is validated is to make sure (in a provable way) the origin of the content is exactly what it claims to be.   I own the virtual machine and it physically resides in Phoenix Arizona in the US.    When your browser connects via https, it asks for the certificate via Apache.  It then takes that certificate and validates it using a higher certificate authority that knows the identity of the authority that grants us our certificate.  So, I think I need to use the certificate that I generated that correctly identifies the location, the domain MichaelKentBurns.com (of which demo is a subdomain) and has my validated email address.  All of that is built into the certificate.   I’ll try to look at this more later today.  Thanks for your efforts.I also want to make sure that we document this and ultimately get it into our training site.  We need to create a security section.  I have a close friend who is a network security expert in the highest levels of internet security.   I am trying to get some little bit of time with him to get pointers to the best sources for us to learn from.  Perhaps I can also get him to review whatever we write.   Stay tuned. Sent from my iPadOn Jul 10, 2024, at 05:18, Destin ASHUZA ***@***.***> wrote:﻿

Does this make sense to you?
It's odd because the Country is US but the state is NK and Locality is Goma.

I generated a new key, but I wanted to know if it is important to specify the country and this other information

**Comment by bahati7** [comment]
I only saw it recently because I didn't get the email notification. But I'll make sure everyone reads it and leaves a comment.

**Comment by MichaelKentBurns** [comment]
I have regenerated a certificate and installed it.
The certificate is now valid and trusted.  You should no longer get a warning. 
Here are the details for the certificate:
![demo MichaelKentBurns com-certificate](https://github.com/user-attachments/assets/8c923237-5952-46f8-8696-1344feece1f2)
