### ISSUE TITLE
We need to query survey responses - not finding cohort-2 guys answers 

### ISSUE THREAD

**Issue by MichaelKentBurns** [MichaelKentBurns/MKB-cohort-1-Demo#25]
You have already provided a link "To display your answers, click here" and that is a good start.   The link is still broken on the demo site but I see it's fixed in the repository.  

When I put in my own email address it seems to work and I can see my survey results.   Good job.
The formatting needs some work, but that is a secondary issue. 

However, when I put in the email address of the cohort-2 guys I get 'User email not found in any answers'.  At first I thought I had mistyped the email address, but even when I cut and paste it from the Answers table itself it is still not working.
Screen capture of the Answers table: 
![Screenshot 2024-07-09 at 10 28 35 AM](https://github.com/MichaelKentBurns/MKB-cohort-1-Demo/assets/5041124/bcbdbdef-4ca7-4c4f-8379-178b7be96907)

Screen capture of the error:
![Screenshot 2024-07-09 at 10 28 11 AM](https://github.com/MichaelKentBurns/MKB-cohort-1-Demo/assets/5041124/8a4c3c76-e9a6-41fa-8a77-8deeb4f1bb4e)

**Comment by bahati7** [comment]
@AshDest you said that cohort2 data is stored in the old database, could you update it?

**Comment by AshDest** [comment]
yes, this information is indeed recorded in the database as visible in the image below of the request on the server

![image](https://github.com/user-attachments/assets/e86ab9cf-b50e-4a47-a7d9-7c598293f8d5)

**Comment by AshDest** [comment]
and here i can see all about surveys:

![image](https://github.com/user-attachments/assets/df126955-d119-44e4-ba73-7a0a5e296396)

**Comment by MichaelKentBurns** [comment]
This issue is resolved with recent changes in the Survey application.  There is now a link that allows a user to query and read their old survey responses.   Thanks guys!
